-- AlterTable
ALTER TABLE `Utilisateurs` ADD COLUMN `pwdtoken` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `timestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `role` VARCHAR(20) NOT NULL DEFAULT 'user';
